# Generated by Django 6.0.4 on 2026-05-03 14:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="institution_logo"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="physical_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="institution",
            name="postal_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="institution",
            name="statement_title",
            field=models.CharField(default="ACCOUNT STATEMENT", max_length=120),
        ),
        migrations.AddField(
            model_name="institution",
            name="website",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
