# Generated by Codex on 2026-04-29

import datetime

from django.db import migrations, models


DEFAULT_ACCOUNTS = (
    {
        "code": "1000",
        "name": "Cash on Hand",
        "type": "asset",
        "normal_balance": "debit",
        "system_code": "cash_on_hand",
        "description": "Cash and teller float used for client-facing collections and payouts.",
    },
    {
        "code": "2000",
        "name": "Client Savings Control",
        "type": "liability",
        "normal_balance": "credit",
        "system_code": "savings_control",
        "description": "Outstanding liability owed to clients for savings balances.",
    },
    {
        "code": "1300",
        "name": "Loans Receivable",
        "type": "asset",
        "normal_balance": "debit",
        "system_code": "loans_receivable",
        "description": "Principal outstanding on disbursed client loans.",
    },
    {
        "code": "4000",
        "name": "Interest Income",
        "type": "income",
        "normal_balance": "credit",
        "system_code": "interest_income",
        "description": "Interest earned on loan repayments.",
    },
)


def forwards(apps, schema_editor):
    Institution = apps.get_model("institutions", "Institution")
    LedgerAccount = apps.get_model("accounting", "LedgerAccount")
    JournalEntry = apps.get_model("accounting", "JournalEntry")

    normal_balance_by_type = {
        "asset": "debit",
        "expense": "debit",
        "liability": "credit",
        "equity": "credit",
        "income": "credit",
    }

    for account in LedgerAccount.objects.all().iterator():
        account.normal_balance = normal_balance_by_type.get(account.type, "debit")
        account.code = (account.code or "").strip().upper()
        account.name = (account.name or "").strip()
        account.description = (account.description or "").strip()
        account.save(
            update_fields=[
                "normal_balance",
                "code",
                "name",
                "description",
                "updated_at",
            ]
        )

    for entry in JournalEntry.objects.all().iterator():
        entry.status = "posted"
        entry.source = "manual"
        entry.source_reference = ""
        entry.entry_date = (entry.posted_at or entry.created_at).date()
        entry.reference = (entry.reference or "").strip()
        entry.description = (entry.description or "").strip()
        entry.save(
            update_fields=[
                "status",
                "source",
                "source_reference",
                "entry_date",
                "reference",
                "description",
                "updated_at",
            ]
        )

    for institution in Institution.objects.all().iterator():
        for config in DEFAULT_ACCOUNTS:
            LedgerAccount.objects.update_or_create(
                institution=institution,
                code=config["code"],
                defaults={
                    "name": config["name"],
                    "type": config["type"],
                    "normal_balance": config["normal_balance"],
                    "description": config["description"],
                    "system_code": config["system_code"],
                    "is_active": True,
                    "allow_manual_entries": True,
                },
            )


def backwards(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="entry_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("savings_deposit", "Savings Deposit"),
                    ("savings_withdrawal", "Savings Withdrawal"),
                    ("loan_disbursement", "Loan Disbursement"),
                    ("loan_repayment", "Loan Repayment"),
                ],
                default="manual",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="source_reference",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("posted", "Posted")],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="ledgeraccount",
            name="allow_manual_entries",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ledgeraccount",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ledgeraccount",
            name="normal_balance",
            field=models.CharField(
                choices=[("debit", "Debit"), ("credit", "Credit")],
                default="debit",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="ledgeraccount",
            name="system_code",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="reference",
            field=models.CharField(max_length=80),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.UniqueConstraint(
                fields=("institution", "reference"),
                name="accounting_journalentry_institution_reference_uniq",
            ),
        ),
    ]
