# Generated by Codex on 2026-04-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0003_accounting_production_mvp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgeraccount",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_accounts",
                to="institutions.institution",
            ),
        ),
    ]
