# Generated by Django 6.0.4 on 2026-04-29 13:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_alter_ledgeraccount_institution"),
        ("institutions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journalentry",
            options={"ordering": ["-entry_date", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="journalentryline",
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="ledgeraccount",
            options={"ordering": ["code", "name"]},
        ),
        migrations.RemoveConstraint(
            model_name="journalentry",
            name="accounting_journalentry_institution_reference_uniq",
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_entries",
                to="institutions.branch",
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="entry_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_entries",
                to="institutions.institution",
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posted_journal_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="source_reference",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="journalentryline",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_lines",
                to="accounting.ledgeraccount",
            ),
        ),
        migrations.AlterField(
            model_name="journalentryline",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="system_code",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name="journalentry",
            unique_together={("institution", "reference")},
        ),
    ]
