# Generated by Codex on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(amount__gt=0),
                name="transaction_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["institution", "created_at"], name="txn_inst_created_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["branch", "created_at"], name="txn_branch_created_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["client", "created_at"], name="txn_client_created_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["category", "direction", "created_at"],
                name="txn_cat_dir_created_idx",
            ),
        ),
    ]
