# Generated by Codex on 2026-04-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
        ("savings", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingsAccountSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_value", models.PositiveIntegerField(default=0)),
                (
                    "branch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings_account_sequence",
                        to="institutions.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savings account sequence",
                "verbose_name_plural": "Savings account sequences",
            },
        ),
        migrations.AddConstraint(
            model_name="savingsaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(balance__gte=0),
                name="savings_account_balance_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="savingsaccount",
            index=models.Index(fields=["client", "status"], name="sav_acc_client_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="savingstransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(amount__gt=0),
                name="savings_transaction_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="savingstransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(balance_after__gte=0),
                name="savings_transaction_balance_after_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="savingstransaction",
            index=models.Index(
                fields=["account", "type", "created_at"],
                name="sav_tx_acct_type_created_idx",
            ),
        ),
    ]
