# Generated by Django 6.0.4 on 2026-05-03 09:46

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0003_savings_module_hardening"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="savingstransaction",
            name="sav_tx_acct_type_created_idx",
        ),
        migrations.AddField(
            model_name="savingstransaction",
            name="transaction_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddIndex(
            model_name="savingstransaction",
            index=models.Index(
                fields=["account", "type", "transaction_date"],
                name="sav_tx_acct_type_transaction_date_idx",
            ),
        ),
    ]
