# Generated by Django 6.0.4 on 2026-05-03 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "savings",
            "0004_remove_savingstransaction_sav_tx_acct_type_created_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="savingstransaction",
            name="sav_tx_acct_type_transaction_date_idx",
        ),
        migrations.AddIndex(
            model_name="savingstransaction",
            index=models.Index(
                fields=["account", "type", "transaction_date", "created_at"],
                name="sav_tx_acct_type_txdate_idx",
            ),
        ),
    ]
