# Generated by Django 6.0.4 on 2026-05-03 13:48

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "savings",
            "0005_remove_savingstransaction_sav_tx_acct_type_transaction_date_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingstransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("withdrawal_charge", "Withdrawal charge"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="SavingsPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        default="Default savings policy", max_length=80, unique=True
                    ),
                ),
                (
                    "minimum_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "withdrawal_charge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Savings policy",
                "verbose_name_plural": "Savings policies",
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("minimum_balance__gte", 0)),
                        name="savings_policy_minimum_balance_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("withdrawal_charge__gte", 0)),
                        name="savings_policy_withdrawal_charge_non_negative",
                    ),
                ],
            },
        ),
    ]
