# Generated by Django 6.0.4 on 2026-04-26 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_initial"),
        ("institutions", "0001_initial"),
        ("loans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loan_applications",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loan_products",
                to="institutions.institution",
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="loans.loanproduct"
            ),
        ),
        migrations.AddField(
            model_name="loanrepayment",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repayments",
                to="loans.loanapplication",
            ),
        ),
        migrations.AddField(
            model_name="loanrepayment",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="repaymentschedule",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule",
                to="loans.loanapplication",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="loanproduct",
            unique_together={("institution", "code")},
        ),
    ]
