# Generated by Codex on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="loanproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(min_amount__gt=0),
                name="loan_product_min_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(max_amount__gt=0),
                name="loan_product_max_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(max_amount__gte=models.F("min_amount")),
                name="loan_product_amount_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(annual_interest_rate__gte=0),
                name="loan_product_interest_rate_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(min_term_months__gt=0),
                name="loan_product_min_term_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(max_term_months__gte=models.F("min_term_months")),
                name="loan_product_term_range_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="loanproduct",
            index=models.Index(fields=["institution", "is_active"], name="loan_prod_inst_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="loanapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(amount__gt=0),
                name="loan_application_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(term_months__gt=0),
                name="loan_application_term_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(principal_balance__gte=0),
                name="loan_application_principal_balance_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(interest_balance__gte=0),
                name="loan_application_interest_balance_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="loanapplication",
            index=models.Index(fields=["client", "status"], name="loan_app_client_status_idx"),
        ),
        migrations.AddIndex(
            model_name="loanapplication",
            index=models.Index(fields=["product", "status"], name="loan_app_product_status_idx"),
        ),
        migrations.AlterModelOptions(
            name="repaymentschedule",
            options={"ordering": ["due_date", "created_at"]},
        ),
        migrations.AddConstraint(
            model_name="repaymentschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(principal_due__gte=0),
                name="repayment_schedule_principal_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="repaymentschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(interest_due__gte=0),
                name="repayment_schedule_interest_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="repaymentschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(paid_amount__gte=0),
                name="repayment_schedule_paid_amount_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="repaymentschedule",
            index=models.Index(fields=["loan", "due_date"], name="loan_sched_loan_due_idx"),
        ),
        migrations.AddIndex(
            model_name="repaymentschedule",
            index=models.Index(fields=["loan", "is_paid"], name="loan_sched_loan_paid_idx"),
        ),
        migrations.AddConstraint(
            model_name="loanrepayment",
            constraint=models.CheckConstraint(
                condition=models.Q(amount__gt=0),
                name="loan_repayment_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanrepayment",
            constraint=models.CheckConstraint(
                condition=models.Q(principal_component__gte=0),
                name="loan_repayment_principal_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanrepayment",
            constraint=models.CheckConstraint(
                condition=models.Q(interest_component__gte=0),
                name="loan_repayment_interest_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="loanrepayment",
            index=models.Index(fields=["loan", "created_at"], name="loan_repay_loan_created_idx"),
        ),
    ]
