# Generated by Django 6.0.4 on 2026-04-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_loans_mvp_hardening"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loanproduct",
            options={"ordering": ["-created_at"]},
        ),
    ]
