# Generated by Django 6.0.4 on 2026-04-30 05:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def migrate_pending_statuses(apps, schema_editor):
    LoanApplication = apps.get_model("loans", "LoanApplication")
    LoanApplication.objects.filter(status="pending").update(status="submitted")


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
        ("loans", "0004_alter_loanproduct_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanApplicationAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("submit", "Submit"),
                            ("start_review", "Start Review"),
                            ("recommend", "Recommend"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("disburse", "Disburse"),
                            ("repay", "Repay"),
                        ],
                        max_length=30,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(blank=True, max_length=20)),
                ("comment", models.TextField(blank=True)),
                ("reference", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "ordering": ["created_at", "id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_loan_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="disbursed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disbursed_loan_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="disbursement_method",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="disbursement_reference",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="recommended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="recommended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommended_loan_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_loan_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_loan_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="default_term_months",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="interest_method",
            field=models.CharField(
                choices=[("flat", "Flat"), ("reducing_balance", "Reducing Balance")],
                default="flat",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="penalty_flat_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="penalty_grace_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="penalty_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="repayment_frequency",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("biweekly", "Biweekly"),
                    ("weekly", "Weekly"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="loanrepayment",
            name="payment_method",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="loanrepayment",
            name="penalty_component",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="loanrepayment",
            name="remaining_balance_after",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("recommended", "Recommended"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("disbursed", "Disbursed"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_pending_statuses, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="loanproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("default_term_months__isnull", True),
                    ("default_term_months__gt", 0),
                    _connector="OR",
                ),
                name="loan_product_default_term_positive_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(("penalty_rate__gte", 0)),
                name="loan_product_penalty_rate_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(("penalty_flat_amount__gte", 0)),
                name="loan_product_penalty_flat_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanrepayment",
            constraint=models.CheckConstraint(
                condition=models.Q(("penalty_component__gte", 0)),
                name="loan_repayment_penalty_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanrepayment",
            constraint=models.CheckConstraint(
                condition=models.Q(("remaining_balance_after__gte", 0)),
                name="loan_repayment_remaining_balance_non_negative",
            ),
        ),
        migrations.AddField(
            model_name="loanapplicationaction",
            name="acted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loan_application_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanapplicationaction",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_history",
                to="loans.loanapplication",
            ),
        ),
        migrations.AddIndex(
            model_name="loanapplicationaction",
            index=models.Index(
                fields=["application", "created_at"],
                name="loans_loana_applica_39862b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loanapplicationaction",
            index=models.Index(
                fields=["action", "created_at"], name="loans_loana_action_54c96f_idx"
            ),
        ),
    ]
