# Generated by Django 6.0.4 on 2026-05-03 19:39

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_journalentry_options_and_more"),
        ("institutions", "0002_institution_logo_institution_physical_address_and_more"),
        ("loans", "0005_loanapplicationaction_loanapplication_approved_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanAppraisal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("modify", "Modify"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recommended_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "recommended_term_months",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "monthly_expenses",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "existing_debt_payments",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "affordability_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "estimated_installment",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("risk_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "savings_balance_snapshot",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "share_capital_snapshot",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("outstanding_loans_snapshot", models.PositiveIntegerField(default=0)),
                ("overdue_loans_snapshot", models.PositiveIntegerField(default=0)),
                ("eligibility_passed", models.BooleanField(default=True)),
                ("collateral_notes", models.TextField(blank=True)),
                ("guarantor_notes", models.TextField(blank=True)),
                ("credit_comments", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="appraised_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="appraised_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appraised_loan_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="eligibility_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="repayment_source",
            field=models.CharField(
                choices=[
                    ("business", "Business"),
                    ("salary", "Salary"),
                    ("farm", "Farm"),
                    ("savings", "Savings"),
                    ("payroll", "Payroll"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="withdrawal_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="withdrawn_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="withdrawn_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="withdrawn_loan_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="debt_to_income_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="funding_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loan_products_funding",
                to="accounting.ledgeraccount",
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="grace_period_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="interest_income_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loan_products_interest_income",
                to="accounting.ledgeraccount",
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="max_amount_to_savings_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="max_amount_to_share_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="max_outstanding_loans",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="minimum_savings_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="minimum_share_capital",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="receivable_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loan_products_receivable",
                to="accounting.ledgeraccount",
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("appraised", "Appraised"),
                    ("recommended", "Recommended"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                    ("disbursed", "Disbursed"),
                    ("closed", "Closed"),
                    ("written_off", "Written Off"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loanapplicationaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("submit", "Submit"),
                    ("start_review", "Start Review"),
                    ("appraise", "Appraise"),
                    ("recommend", "Recommend"),
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("withdraw", "Withdraw"),
                    ("disburse", "Disburse"),
                    ("repay", "Repay"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="interest_method",
            field=models.CharField(
                choices=[
                    ("flat", "Flat"),
                    ("reducing_balance", "Reducing Balance"),
                    ("declining_balance", "Declining Balance"),
                    ("interest_only", "Interest Only"),
                ],
                default="flat",
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="loanproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(("grace_period_days__gte", 0)),
                name="loan_product_grace_period_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_savings_balance__gte", 0)),
                name="loan_product_min_savings_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_share_capital__gte", 0)),
                name="loan_product_min_share_capital_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_outstanding_loans__isnull", True),
                    ("max_outstanding_loans__gt", 0),
                    _connector="OR",
                ),
                name="loan_product_max_outstanding_loans_positive_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_amount_to_savings_ratio__isnull", True),
                    ("max_amount_to_savings_ratio__gt", 0),
                    _connector="OR",
                ),
                name="loan_product_savings_ratio_positive_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_amount_to_share_ratio__isnull", True),
                    ("max_amount_to_share_ratio__gt", 0),
                    _connector="OR",
                ),
                name="loan_product_share_ratio_positive_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("debt_to_income_limit__isnull", True),
                    ("debt_to_income_limit__gt", 0),
                    _connector="OR",
                ),
                name="loan_product_dti_limit_positive_or_null",
            ),
        ),
        migrations.AddField(
            model_name="loanappraisal",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appraisals",
                to="loans.loanapplication",
            ),
        ),
        migrations.AddField(
            model_name="loanappraisal",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loan_appraisals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="loanappraisal",
            index=models.Index(
                fields=["application", "created_at"], name="loan_appr_app_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanappraisal",
            index=models.Index(
                fields=["recommendation", "created_at"],
                name="loan_appr_reco_created_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanappraisal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recommended_amount__isnull", True),
                    ("recommended_amount__gt", 0),
                    _connector="OR",
                ),
                name="loan_appraisal_recommended_amount_positive_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanappraisal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recommended_term_months__isnull", True),
                    ("recommended_term_months__gt", 0),
                    _connector="OR",
                ),
                name="loan_appraisal_recommended_term_positive_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanappraisal",
            constraint=models.CheckConstraint(
                condition=models.Q(("monthly_income__gte", 0)),
                name="loan_appraisal_monthly_income_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanappraisal",
            constraint=models.CheckConstraint(
                condition=models.Q(("monthly_expenses__gte", 0)),
                name="loan_appraisal_monthly_expenses_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanappraisal",
            constraint=models.CheckConstraint(
                condition=models.Q(("existing_debt_payments__gte", 0)),
                name="loan_appraisal_existing_debt_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanappraisal",
            constraint=models.CheckConstraint(
                condition=models.Q(("affordability_amount__gte", 0)),
                name="loan_appraisal_affordability_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanappraisal",
            constraint=models.CheckConstraint(
                condition=models.Q(("estimated_installment__gte", 0)),
                name="loan_appraisal_estimated_installment_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanappraisal",
            constraint=models.CheckConstraint(
                condition=models.Q(("savings_balance_snapshot__gte", 0)),
                name="loan_appraisal_savings_snapshot_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanappraisal",
            constraint=models.CheckConstraint(
                condition=models.Q(("share_capital_snapshot__gte", 0)),
                name="loan_appraisal_share_snapshot_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanappraisal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("risk_score__isnull", True),
                    models.Q(("risk_score__gte", 0), ("risk_score__lte", 100)),
                    _connector="OR",
                ),
                name="loan_appraisal_risk_score_range",
            ),
        ),
    ]
