# Generated by Django 6.0.4 on 2026-05-02 14:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0005_client_created_by_client_updated_by"),
        ("institutions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareAccountSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_value", models.PositiveIntegerField(default=0)),
                (
                    "branch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_account_sequence",
                        to="institutions.branch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShareProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("code", models.SlugField()),
                ("nominal_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("minimum_shares", models.PositiveIntegerField(default=1)),
                ("maximum_shares", models.PositiveIntegerField(blank=True, null=True)),
                ("allow_dividends", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="share_products",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShareAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=40, unique=True),
                ),
                ("shares", models.PositiveIntegerField(default=0)),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="share_accounts",
                        to="clients.client",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="shares.shareproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShareTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("redeem", "Redeem"),
                            ("transfer_in", "Transfer In"),
                            ("transfer_out", "Transfer Out"),
                            ("dividend", "Dividend"),
                        ],
                        max_length=20,
                    ),
                ),
                ("shares", models.PositiveIntegerField(default=0)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("balance_after", models.PositiveIntegerField(default=0)),
                ("reference", models.CharField(max_length=80, unique=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="shares.shareaccount",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="shareproduct",
            index=models.Index(
                fields=["institution", "status"], name="shares_shar_institu_898035_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shareproduct",
            unique_together={("institution", "code")},
        ),
        migrations.AddIndex(
            model_name="shareaccount",
            index=models.Index(
                fields=["client", "status"], name="shares_shar_client__443566_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shareaccount",
            index=models.Index(
                fields=["product", "status"], name="shares_shar_product_759358_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shareaccount",
            constraint=models.UniqueConstraint(
                fields=("client", "product"), name="unique_client_share_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="shareaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("shares__gte", 0)),
                name="share_account_shares_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="shareaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_value__gte", 0)),
                name="share_account_value_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="sharetransaction",
            index=models.Index(
                fields=["account", "type", "created_at"],
                name="shares_shar_account_de5bc3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharetransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="share_transaction_amount_non_negative",
            ),
        ),
    ]
