# Generated by Django 6.0.4 on 2026-05-03 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0002_institution_logo_institution_physical_address_and_more"),
        ("shares", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sharetransaction",
            name="share_transaction_amount_non_negative",
        ),
        migrations.AddConstraint(
            model_name="shareproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(("nominal_price__gt", 0)),
                name="share_product_nominal_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="shareproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_shares__gte", 1)),
                name="share_product_minimum_shares_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="shareproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("maximum_shares__isnull", True),
                    ("maximum_shares__gte", 1),
                    _connector="OR",
                ),
                name="share_product_maximum_shares_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="shareproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("maximum_shares__isnull", True),
                    ("maximum_shares__gte", models.F("minimum_shares")),
                    _connector="OR",
                ),
                name="share_product_maximum_gte_minimum",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharetransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="share_transaction_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharetransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance_after__gte", 0)),
                name="share_transaction_balance_after_non_negative",
            ),
        ),
    ]
