# Generated by Codex on 2026-05-04

import django.db.models.deletion
from django.db import migrations, models


def populate_audit_scope_fields(apps, schema_editor):
    AuditLog = apps.get_model("audit", "AuditLog")

    for log in AuditLog.objects.select_related("user", "branch", "institution").all().iterator():
        action = str(log.action or "")
        parts = [part.strip() for part in action.split(".") if part.strip()]
        module = parts[0] if len(parts) >= 1 else ""
        resource = parts[1] if len(parts) >= 2 else ""
        event = ".".join(parts[2:]) if len(parts) >= 3 else ""

        institution_id = getattr(log, "institution_id", None)
        branch_id = getattr(log, "branch_id", None)
        user = getattr(log, "user", None)

        if branch_id is None and user and getattr(user, "branch_id", None):
            branch_id = user.branch_id

        client_profile = getattr(user, "client_profile", None) if user else None
        if branch_id is None and client_profile and getattr(client_profile, "branch_id", None):
            branch_id = client_profile.branch_id

        if institution_id is None and user and getattr(user, "institution_id", None):
            institution_id = user.institution_id

        if institution_id is None and client_profile and getattr(client_profile, "institution_id", None):
            institution_id = client_profile.institution_id

        if institution_id is None and branch_id and user and getattr(user, "branch", None):
            institution_id = getattr(user.branch, "institution_id", None)

        AuditLog.objects.filter(pk=log.pk).update(
            institution_id=institution_id,
            branch_id=branch_id,
            module=module,
            resource=resource,
            event=event,
            request_path=getattr(log, "request_path", "") or "",
        )


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0002_institution_logo_institution_physical_address_and_more"),
        ("audit", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="institutions.branch",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="event",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="institutions.institution",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="module",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="request_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="resource",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["module", "resource", "event"],
                name="audit_module_resource_event_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["institution", "branch", "created_at"],
                name="audit_scope_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "created_at"],
                name="audit_user_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "created_at"],
                name="audit_action_created_idx",
            ),
        ),
        migrations.RunPython(populate_audit_scope_fields, migrations.RunPython.noop),
    ]
