# Generated by Django 6.0.4 on 2026-05-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_auditlog_scope_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="aud_mod_res_evt_idx",
            old_name="audit_module_resource_event_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="aud_scope_cr_idx",
            old_name="audit_scope_created_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="aud_usr_cr_idx",
            old_name="audit_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="aud_act_cr_idx",
            old_name="audit_action_created_idx",
        ),
    ]
