# Generated by Codex on 2026-04-29

import django.db.models.deletion
from django.db import migrations, models


def seed_client_member_sequences(apps, schema_editor):
    Branch = apps.get_model("institutions", "Branch")
    Client = apps.get_model("clients", "Client")
    ClientMemberSequence = apps.get_model("clients", "ClientMemberSequence")

    for branch in Branch.objects.all().iterator():
        member_numbers = Client.objects.filter(branch=branch).values_list("member_number", flat=True)
        last_value = 0

        for member_number in member_numbers:
            if not member_number:
                continue

            suffix = member_number.rsplit("-", 1)[-1]
            if suffix.isdigit():
                last_value = max(last_value, int(suffix))

        if not last_value:
            last_value = Client.objects.filter(branch=branch).count()

        if last_value:
            ClientMemberSequence.objects.update_or_create(
                branch=branch,
                defaults={"last_value": last_value},
            )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0001_initial"),
        ("clients", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientMemberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_value", models.PositiveIntegerField(default=0)),
                (
                    "branch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_member_sequence",
                        to="institutions.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client member sequence",
                "verbose_name_plural": "Client member sequences",
            },
        ),
        migrations.RunPython(seed_client_member_sequences, noop_reverse),
    ]
