# Generated by Codex on 2026-04-29

from django.db import migrations, models


def normalize_client_statuses(apps, schema_editor):
    Client = apps.get_model("clients", "Client")
    Client.objects.filter(status="pending").update(status="inactive")
    Client.objects.filter(status="closed").update(status="inactive")


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0003_clientmembersequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("female", "Female"),
                    ("male", "Male"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer Not To Say"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(normalize_client_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("blacklisted", "Blacklisted"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
