# Generated by Django 6.0.4 on 2026-05-04 08:20

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_created_by_client_updated_by'),
        ('institutions', '0002_institution_logo_institution_physical_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('blacklisted', 'Blacklisted')], max_length=20)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='employer',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='client',
            name='is_watchlist_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='kyc_level',
            field=models.CharField(blank=True, choices=[('level_1', 'Level 1'), ('level_2', 'Level 2'), ('level_3', 'Level 3')], max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='membership_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('organization', 'Organization')], default='individual', max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='client',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile photo'),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='client',
            name='risk_rating',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='verification_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('blacklisted', 'Blacklisted')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['institution', 'branch', 'status'], name='client_inst_branch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['kyc_status', 'risk_rating'], name='client_kyc_risk_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['membership_type', 'joining_date'], name='client_member_type_join_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_watchlist_flagged'], name='client_watchlist_idx'),
        ),
        migrations.AddField(
            model_name='clientstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientstatushistory',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='clients.client'),
        ),
        migrations.AddIndex(
            model_name='clientstatushistory',
            index=models.Index(fields=['client', 'created_at'], name='client_status_hist_client_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clientstatushistory',
            index=models.Index(fields=['to_status', 'created_at'], name='client_status_hist_status_created_idx'),
        ),
    ]
