# Generated by Django 6.0.4 on 2026-05-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_clientstatushistory_client_employer_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="clientstatushistory",
            new_name="cli_stat_cl_cr_idx",
            old_name="client_status_hist_client_created_idx",
        ),
        migrations.RenameIndex(
            model_name="clientstatushistory",
            new_name="cli_stat_st_cr_idx",
            old_name="client_status_hist_status_created_idx",
        ),
    ]
